apiVersion: v1
kind: Pod
metadata:
  name: secret-1401
  namespace: admin1401
spec:
  containers:
  - name: secret-admin
    image: busybox
    args:
      - sleep
      - "4800"
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true

  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret 
